# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build for Github Pages

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js and yarn cache
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"

      - name: install yarn
        run: npm install -g yarn

      - name: install
        run: yarn install --frozen-lockfile

      - name: test
        run: yarn test

      - name: build
        run: yarn build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
